# Generated by Django 6.0.6 on 2026-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_instructor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
