# Generated by Django 6.0.6 on 2026-07-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_enrollment_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.instructor'),
            preserve_default=False,
        ),
    ]
