# Generated by Django 6.0.6 on 2026-07-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
