# Generated by Django 6.0.6 on 2026-07-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_documents_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_enrolled',
        ),
    ]
