# Generated by Django 6.0.6 on 2026-07-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_enrollment_is_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumnailUrl',
            new_name='thumbnailUrl',
        ),
    ]
