# Generated by Django 6.0.6 on 2026-07-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mcq_options_quiz_mcq_quiz_shortanswers_truefalse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
