# Generated by Django 6.0.6 on 2026-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalse',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
