# Generated by Django 6.0.6 on 2026-07-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_truefalse_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswers',
            name='correct',
            field=models.CharField(max_length=255),
        ),
    ]
