# Generated by Django 6.0.6 on 2026-07-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_shortanswers_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'Ai'), ('human', 'Human')], max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='app.aitutor')),
            ],
        ),
    ]
