# Generated by Django 6.0.6 on 2026-07-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_aitutor_createdat_chatmessages_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitutor',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='video',
            name='createdAt',
        ),
    ]
