# Generated by Django 6.0.6 on 2026-07-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_aitutor_createdat_remove_documents_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='createdAt',
        ),
    ]
