# Generated by Django 6.0.6 on 2026-07-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_chatmessages_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='reviwedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
