# Generated by Django 6.0.6 on 2026-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_aitutor_createdat_chatmessages_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
