# Generated by Django 6.0.6 on 2026-07-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_flashcardreview_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='reviwedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='FlashCardReview',
        ),
    ]
