# Generated by Django 6.0.6 on 2026-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_flashcardreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
