# Generated by Django 6.0.6 on 2026-07-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizperformnace',
            name='correct',
            field=models.FloatField(default=0),
        ),
    ]
