# Generated by Django 6.0.6 on 2026-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_quizperformnace_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
