# Generated by Django 6.0.6 on 2026-07-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_quiz_attempted_quiz_correct_quiz_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
        migrations.AlterField(
            model_name='documents',
            name='fileUrl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
