# Generated by Django 6.0.6 on 2026-07-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_flashcard_user_alter_documents_fileurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='correct',
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='flahscard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.flashcard'),
            preserve_default=False,
        ),
    ]
