# Generated by Django 6.0.6 on 2026-07-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_flashcard_correct_flashcardreview_flahscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardreview',
            name='total',
        ),
    ]
