# Generated by Django 6.0.6 on 2026-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_flashcardreview_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardreview',
            old_name='flahscard',
            new_name='flashcard',
        ),
        migrations.RemoveField(
            model_name='flashcardreview',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='flashcardreview',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='flashcardreview',
            name='correct',
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good'), (3, 'Easy')], default=1),
            preserve_default=False,
        ),
    ]
