# Generated by Django 6.0.6 on 2026-07-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_flahscard_flashcardreview_flashcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good')]),
        ),
    ]
