# Generated by Django 6.0.6 on 2026-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_flashcardreview_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good'), (3, 'Easy')]),
        ),
    ]
