# Generated by Django 6.0.6 on 2026-07-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_flashcardreview_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardreview',
            name='quality',
        ),
    ]
