# Generated by Django 6.0.6 on 2026-07-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_flashcardreview_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardreview',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good'), (3, 'Easy')], default=2),
            preserve_default=False,
        ),
    ]
