# Generated by Django 6.0.6 on 2026-07-20 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_flashcardreview_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='reviwedAt',
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='introduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='next_review',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='repitition',
            field=models.IntegerField(default=0),
        ),
    ]
