# Generated by Django 6.0.6 on 2026-07-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_flashcard_reviwedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardreview',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
    ]
