# Generated by Django 6.0.6 on 2026-07-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_flashcardreview_accuracy_flashcardreview_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardreview',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
