# Generated by Django 6.0.6 on 2026-07-20 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_flashcardreview_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardreview',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='flashcardreview',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='flashcardreview',
            name='marks',
        ),
        migrations.AlterField(
            model_name='flashcardreview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='flashcardreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlashCardReviewCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
