# Generated by Django 6.0.6 on 2026-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_flashcardreview_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardreview',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good'), (3, 'Easy')], default=0),
        ),
    ]
