# Generated by Django 6.0.6 on 2026-07-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_flashcardreview_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
    ]
