# Generated by Django 6.0.6 on 2026-07-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
