# Generated by Django 6.0.6 on 2026-07-29 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_enrollment_completed_enrollment_total_docprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='docprogress',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docprogress',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='docprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
