# Generated by Django 6.0.6 on 2026-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_docprogress_user_remove_enrollment_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
