# Generated by Django 6.0.6 on 2026-08-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_enrollment_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
