# Generated by Django 6.0.6 on 2026-08-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_createdat_documents_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(default=123456789),
            preserve_default=False,
        ),
    ]
